import 'package:get/get_utils/src/extensions/internacionalization.dart';

class HardCode {
  static List<String> provinces = [
    'Baghdad'.tr,
    'Basra'.tr,
    'Maysan'.tr,
    'Dhi Qar'.tr,
    'Qadisiyah'.tr,
    'Wasit'.tr,
    'Babylon'.tr,
    'Najaf'.tr,
    'Karbala'.tr,
    'Al-Anbar'.tr,
    'Salahuddin'.tr,
    'Diyala'.tr,
    'Kirkuk'.tr,
    'Sulaymaniyah'.tr,
    'Erbil'.tr,
    'Dohuk'.tr,
    'Halabja'.tr,
  ];

  List<String> provincesAr = [
    'بغداد',
    'البصرة',
    'الميسان',
    'ذي قار',
    'المثنى',
    'القادسية',
    'واسط',
    'القادسية',
    'بابل',
    'النجف',
    'كربلاء',
    'الأنبار',
    'صلاح الدين',
    'ديالى',
    'كركوك',
    'السليمانية',
    'أربيل',
    'دهوك',
    'حلبجة',
  ];
  List<String> provincesKu = [
    'باگداد',
    'بصرە',
    'میسان',
    'دهۆک',
    'موسڵ',
    'ناوجف',
    'کەربلاء',
    'سلێمانی',
    'هەولێر',
    'کەرکووک',
    'دهەولیە',
    'بابل',
    'نەینووف',
    'سلاحەدین',
    'کەندال',
    'کەلار',
    'هەڵەبجە',
    'بەغداڵ',
  ];

  static List<String> carColors = [
    'Black'.tr,
    'White'.tr,
    'Silver'.tr,
    'Gray'.tr,
    'Blue'.tr,
    'Red'.tr,
    'Green'.tr,
    'Yellow'.tr,
    'Orange'.tr,
    'Brown'.tr,
    'Gold'.tr,
    'Beige'.tr,
    'Burgundy'.tr,
    'Purple'.tr,
    'Pink'.tr,
    'Champagne'.tr,
    'Bronze'.tr,
    'Charcoal'.tr,
    'Gunmetal'.tr,
    'Navy Blue'.tr,
    'Sky Blue'.tr,
    'Teal'.tr,
    'Olive Green'.tr,
    'Lime Green'.tr,
    'Amber'.tr,
    'Maroon'.tr,
    'Ruby Red'.tr,
    'Crimson'.tr,
    'Magenta'.tr,
    'Pearl White'.tr,
  ];

  static List<String> engineSizes = [
    "1.0",
    "1.1",
    "1.2",
    "1.3",
    "1.4",
    "1.5",
    "1.6",
    "1.7",
    "1.8",
    "1.9",
    "2.0",
    "2.1",
    "2.2",
    "2.3",
    "2.4",
    "2.5",
    "2.6",
    "2.7",
    "2.8",
    "2.9",
    "3.0",
    "3.1",
    "3.2",
    "3.3",
    "3.4",
    "3.5",
    "3.6",
    "3.7",
    "3.8",
    "3.9",
    "4.0",
    "4.1",
    "4.2",
    "4.3",
    "4.4",
    "4.5",
    "4.6",
    "4.7",
    "4.8",
    "4.9",
    "5.0",
    "5.1",
    "5.2",
    "5.3",
    "5.4",
    "5.5",
    "5.6",
    "5.7",
    "5.8",
    "5.9",
    "6.0",
    "6.1",
    "6.2",
    "6.3",
    "6.4",
    "6.5",
    "6.6",
    "6.7",
    "6.8",
    "6.9",
    "7.0",
    "7.1",
    "7.2",
    "7.3",
    "7.4",
    "7.5",
    "7.6",
    "7.7",
    "7.8",
    "7.9",
    "8.0",
    "8.1",
    "8.2",
    "8.3",
    "8.4",
    "8.5",
    "8.6",
    "8.7",
    "8.8",
    "8.9",
    "9.0",
    "9.1",
    "9.2",
    "9.3",
    "9.4",
    "9.5",
    "9.6",
    "9.7",
    "9.8",
    "9.9",
    "10.0"
  ];

  // static Map<String, String> provinces = {
  //   'Baghdad': 'Baghdad',
  //   'Basra': 'Basra',
  //   'Maysan': 'Maysan',
  //   'Dhi-Qar': 'Dhi Qar',
  //   'Muthanna': 'Muthanna',
  //   'Qadisiyah': 'Qadisiyah',
  //   'Wasit': 'Wasit',
  //   'Al-Qadisiyyah': 'Al-Qadisiyyah',
  //   'Babylon': 'Babylon',
  //   'Najaf': 'Najaf',
  //   'Karbala': 'Karbala',
  //   'Al-Anbar': 'Al-Anbar',
  //   'Salahuddin': 'Salahuddin',
  //   'Diyala': 'Diyala',
  //   'Kirkuk': 'Kirkuk',
  //   'Sulaymaniyah': 'Sulaymaniyah',
  //   'Erbil': 'Erbil',
  //   'Dohuk': 'Dohuk',
  //   'Halabja': 'Halabja',
  // };

  static List<Map<String, String>> madeTo = [
    {
      "us": "USA".tr,
    },
    {
      "ur": "Europe".tr,
    },
    {
      "ar": "Gulf".tr,
    },
    {
      "ca": "CA".tr,
    }
  ];

  static List<Map<String, String>> creditTypes = [
    {
      "Asiacell": "Asiacell".tr,
    },
    {
      "Zain": "Zain".tr,
    },
    {
      "Korek": "Korek".tr,
    },

  ];

}

String? getValueHardCodeMadeToByKey(String key) {
  final map = HardCode.madeTo
      .firstWhere((item) => item.containsKey(key), orElse: () => {});
  return map[key];
}