class HardCode {
  static List<String> provinces = [
    'Baghdad',
    'Basra',
    'Maysan',
    'Dhi Qar',
    'Muthanna',
    'Qadisiyah',
    'Wasit',
    'Al-Qādisiyyah',
    'Babylon',
    'Najaf',
    'Karbala',
    'Al-Anbar',
    'Salahuddin',
    'Diyala',
    'Kirkuk',
    'Sulaymaniyah',
    'Erbil',
    'Dohuk',
    'Halabja',
  ];

  List<String> provincesAr = [
    'بغداد',
    'البصرة',
    'الميسان',
    'ذي قار',
    'المثنى',
    'القادسية',
    'واسط',
    'القادسية',
    'بابل',
    'النجف',
    'كربلاء',
    'الأنبار',
    'صلاح الدين',
    'ديالى',
    'كركوك',
    'السليمانية',
    'أربيل',
    'دهوك',
    'حلبجة',
  ];
  List<String> provincesKu = [
    'باگداد',
    'بصرە',
    'میسان',
    'دهۆک',
    'موسڵ',
    'ناوجف',
    'کەربلاء',
    'سلێمانی',
    'هەولێر',
    'کەرکووک',
    'دهەولیە',
    'بابل',
    'نەینووف',
    'سلاحەدین',
    'کەندال',
    'کەلار',
    'هەڵەبجە',
    'بەغداڵ',
  ];

  static List<String> carColors = [
    'Black',
    'White',
    'Silver',
    'Gray',
    'Blue',
    'Red',
    'Green',
    'Yellow',
    'Orange',
    'Brown',
    'Gold',
    'Beige',
    'Burgundy',
    'Purple',
    'Pink',
    'Champagne',
    'Bronze',
    'Charcoal',
    'Gunmetal',
    'Navy Blue',
    'Sky Blue',
    'Teal',
    'Olive Green',
    'Lime Green',
    'Amber',
    'Maroon',
    'Ruby Red',
    'Crimson',
    'Magenta',
    'Pearl White',
  ];
}
